apiVersion: v1
kind: Service
metadata:
  name: minecraft-ctf-tcp
  namespace: ctf
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
  labels:
    app: minecraft-ctf
    team: ctf
spec:
  selector:
    app: minecraft-ctf
  ports:
    - name: minecraft
      port: 25565
      targetPort: 25565
      protocol: TCP
  type: LoadBalancer
