# PaperMC CTF server configuration
level-name=world

gamemode=survival
force-gamemode=true
difficulty=normal
pvp=false
spawn-protection=0

allow-flight=true
online-mode=false

log-ips=false

enforce-whitelist=false
white-list=false

max-players=50
view-distance=10
simulation-distance=10

motd=\u00A7cNav Security Champions \u00A7f- Minecraft Hacking CTF
