name: Build and push image

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      deploy-infra:
        description: "Deploy PVC and Service (only needed once)"
        type: boolean
        default: false
concurrency:
  group: ctf
  cancel-in-progress: true

jobs:
  build:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    outputs:
      image: ${{ steps.docker-build-push.outputs.image }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Build and push with NAIS
        uses: nais/docker-build-push@cd5ec5663feb0e05c3fa374d1fb442605b046c6b
        id: docker-build-push
        with:
          team: appsec-ctf

  deploy-infra:
    name: Deploy PVC
    needs: build
    if: ${{ inputs.deploy-infra == true }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Deploy PVC
        uses: nais/deploy/actions/deploy@8a6fb62e73f837af6287d5db84a46ea96aa6c30d # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/minecraft-pvc.yaml

  deploy:
    name: Deploy application
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Deploy minecraft-ctf
        uses: nais/deploy/actions/deploy@8a6fb62e73f837af6287d5db84a46ea96aa6c30d # v2
        env:
          CLUSTER: dev-gcp
          RESOURCE: .nais/minecraft.yaml
          IMAGE: ${{ needs.build.outputs.image }}
